### PR TITLE
Port to JupyterLab 3

### PR DESCRIPTION
**Pull request by fcollonval**
To fix:
- [x] it does not work in federated mode
- [x] Some styles are broken in notebook diff

### CODE REVIEW

**Comment by bollwyvl** [comment]
Happy to help if we can find tasks to divide and conquer, but a little insight into the path forward on #27 would help!

**Comment by bollwyvl** [comment]
The sub-pr is looking good: https://github.com/bollwyvl/pull-requests/pull/3/checks?check_run_id=2106577541

**Comment by fcollonval** [comment]
Let's merge this overdue port - I will publish a version for JLab 3 within the week.

**Comment by bollwyvl** [comment]
I'm kinda out of pocket at the moment, but will definitely see about getting that binder PR up against this when next i have the chance!

**Pull request merged**
